# Default values.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

name: cma-operator
image:
  repo: quay.io/samsung_cnct/cma-operator:prod

